/**
 * This file declares the BuildInfo
 *
 * *************************
 * DO NOT EDIT THIS FILE !!!
 * *************************
 *
 * This file is automatically generated by the script generateBuildInfoFile.tcl
 * (c) Copyright 2018 Telops Inc.
 *
*/
#ifndef BUILDINFO_H
#define BUILDINFO_H
 
#ifdef ARCH_FPGA_160
 
#define SVN_HARDWARE_REV 25353
#define SVN_SOFTWARE_REV      25353
 #define SVN_BOOTLOADER_REV   29266
 #define SVN_COMMON_REV      29266
 
#define SVN_UNCOMMITTED_CHANGES  ((SVN_HARDWARE_REV < 0) || (SVN_SOFTWARE_REV < 0) || (SVN_BOOTLOADER_REV < 0) || (SVN_COMMON_REV < 0))
 
#if SVN_UNCOMMITTED_CHANGES
#warning Uncommitted changes detected
#endif
 
#elif defined(ARCH_FPGA_325)
 
#define SVN_HARDWARE_REV 29272
#define SVN_SOFTWARE_REV      29286
 #define SVN_BOOTLOADER_REV   29266
 #define SVN_COMMON_REV      29266
 
#define SVN_UNCOMMITTED_CHANGES  ((SVN_HARDWARE_REV < 0) || (SVN_SOFTWARE_REV < 0) || (SVN_BOOTLOADER_REV < 0) || (SVN_COMMON_REV < 0))
 
#if SVN_UNCOMMITTED_CHANGES
#warning Uncommitted changes detected
#endif
 
#endif  // FPGA_ARCH Check
 
#endif // BUILDINFO_H
