# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_c_counter_binary_v12_0_0/histogram_axis_tmi_c_counter_binary_v12_0_0.xci
# IP: The module: 'histogram_axis_tmi_c_counter_binary_v12_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_c_counter_binary_v12_0_0/histogram_axis_tmi_c_counter_binary_v12_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'histogram_axis_tmi_c_counter_binary_v12_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_c_counter_binary_v12_0_0/histogram_axis_tmi_c_counter_binary_v12_0_0.xci
# IP: The module: 'histogram_axis_tmi_c_counter_binary_v12_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_c_counter_binary_v12_0_0/histogram_axis_tmi_c_counter_binary_v12_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'histogram_axis_tmi_c_counter_binary_v12_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
