################### DDR3 ######################
#Unused IO (require to be define manually for BD with MIG that only manage 2DDR)

set_property -dict {PACKAGE_PIN AF17 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[32]]
set_property -dict {PACKAGE_PIN AE17 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[33]]
set_property -dict {PACKAGE_PIN AF14 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[34]]
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[35]]
set_property -dict {PACKAGE_PIN AD15 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[36]]
set_property -dict {PACKAGE_PIN AE15 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[37]]
set_property -dict {PACKAGE_PIN AF19 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[38]]
set_property -dict {PACKAGE_PIN AF20 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[39]]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[40]]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[41]]
set_property -dict {PACKAGE_PIN AC14 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[42]]
set_property -dict {PACKAGE_PIN AD14 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[43]]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[44]]
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[45]]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[46]]
set_property -dict {PACKAGE_PIN AA17 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[47]]
set_property -dict {PACKAGE_PIN AD18 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[48]]
set_property -dict {PACKAGE_PIN AC18 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[49]]
set_property -dict {PACKAGE_PIN AC17 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[50]]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[51]]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[52]]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[53]]
set_property -dict {PACKAGE_PIN AD19 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[54]]
set_property -dict {PACKAGE_PIN AC19 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[55]]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[56]]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[57]]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[58]]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[59]]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[60]]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[61]]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[62]]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dq[63]]

set_property -dict {PACKAGE_PIN AD16 IOSTANDARD SSTL15 slew SLOW} [get_ports CAL_DDR_dm[4]]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD SSTL15 slew SLOW} [get_ports CAL_DDR_dm[5]]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD SSTL15 slew SLOW} [get_ports CAL_DDR_dm[6]]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD SSTL15 slew SLOW} [get_ports CAL_DDR_dm[7]]

set_property -dict {PACKAGE_PIN AF18 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_n[4]]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_n[5]]
set_property -dict {PACKAGE_PIN AE20 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_n[6]]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_n[7]]

set_property -dict {PACKAGE_PIN AE18 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_p[4]]
set_property -dict {PACKAGE_PIN Y15 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_p[5]]
set_property -dict {PACKAGE_PIN AD20 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_p[6]]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD DIFF_SSTL15_T_DCI slew SLOW} [get_ports CAL_DDR_dqs_p[7]]
