# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_blk_mem_gen_v8_1_0/histogram_axis_tmi_blk_mem_gen_v8_1_0.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_blk_mem_gen_v8_1_0/histogram_axis_tmi_blk_mem_gen_v8_1_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.data/wt [current_project]
set_property parent.project_dir D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist [current_project]
synth_design -top histogram_axis_tmi_blk_mem_gen_v8_1_0 -part xc7k160tfbg676-1 -mode out_of_context

rename_ref -prefix_all histogram_axis_tmi_blk_mem_gen_v8_1_0
write_checkpoint -noxdef histogram_axis_tmi_blk_mem_gen_v8_1_0.dcp
report_utilization -file histogram_axis_tmi_blk_mem_gen_v8_1_0_utilization_synth.rpt -pb histogram_axis_tmi_blk_mem_gen_v8_1_0_utilization_synth.pb
if { [catch {
  file copy -force D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.runs/histogram_axis_tmi_blk_mem_gen_v8_1_0_synth_1/histogram_axis_tmi_blk_mem_gen_v8_1_0.dcp D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_blk_mem_gen_v8_1_0/histogram_axis_tmi_blk_mem_gen_v8_1_0.dcp
  write_verilog -force -mode synth_stub D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_blk_mem_gen_v8_1_0/histogram_axis_tmi_blk_mem_gen_v8_1_0_stub.v
  write_verilog -force -mode funcsim D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_blk_mem_gen_v8_1_0/histogram_axis_tmi_blk_mem_gen_v8_1_0_funcsim.v
  write_vhdl -force -mode funcsim D:/Telops/FIR-00251-Proc/src/AEC/HDL/netlist/hdl_netlist/histogram_axis_tmi.srcs/sources_1/ip/histogram_axis_tmi_blk_mem_gen_v8_1_0/histogram_axis_tmi_blk_mem_gen_v8_1_0_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
