/**
 * @file CalibImageCorrectionFile.h
 * Camera image correction calibration file structure declaration.
 *
 * This file declares the camera image correction calibration file structure.
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2016 Telops Inc.
 */

#ifndef CALIBIMAGECORRECTIONFILE_H
#define CALIBIMAGECORRECTIONFILE_H

#include "CalibFiles.h"
#include "CalibActualizationFile_v1.h"
#include "CalibImageCorrectionFile_v2.h"
#include "FileInfo.h"
#include <stdint.h>

// Calibration image correction macros versioning
#define CALIBIMAGECORRECTION_FILEMAJORVERSION      VER_MACRO(CALIBIMAGECORRECTION_FILEMAJORVERSION, CALIBFILES_VERSION)
#define CALIBIMAGECORRECTION_FILEMINORVERSION      VER_MACRO(CALIBIMAGECORRECTION_FILEMINORVERSION, CALIBFILES_VERSION)
#define CALIBIMAGECORRECTION_FILESUBMINORVERSION   VER_MACRO(CALIBIMAGECORRECTION_FILESUBMINORVERSION, CALIBFILES_VERSION)

#define CALIBIMAGECORRECTION_IMAGECORRECTIONFILEHEADER_SIZE          VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONFILEHEADER_SIZE, CALIBFILES_VERSION)

#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATAHEADER_SIZE          VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATAHEADER_SIZE, CALIBFILES_VERSION)

#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_SIZE                VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_SIZE, CALIBFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_MASK      VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_MASK, CALIBFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SHIFT     VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SHIFT, CALIBFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SIGNPOS   VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SIGNPOS, CALIBFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_MASK    VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_MASK, CALIBFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_SHIFT   VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_SHIFT, CALIBFILES_VERSION)

// Calibration image correction types versioning
#define CalibImageCorrection_ImageCorrectionFileHeader_t    VER_TYPE(CalibImageCorrection_ImageCorrectionFileHeader, CALIBFILES_VERSION)
#define CalibImageCorrection_ImageCorrectionDataHeader_t    VER_TYPE(CalibImageCorrection_ImageCorrectionDataHeader, CALIBFILES_VERSION)

// Calibration image correction function versioning
#define CalibImageCorrection_WriteImageCorrectionFileHeader    VER_FUN(CalibImageCorrection_WriteImageCorrectionFileHeader, CALIBFILES_VERSION)
#define CalibImageCorrection_WriteImageCorrectionDataHeader    VER_FUN(CalibImageCorrection_WriteImageCorrectionDataHeader, CALIBFILES_VERSION)

uint32_t CalibImageCorrection_ParseImageCorrectionFileHeader(int fd, CalibImageCorrection_ImageCorrectionFileHeader_t *hdr, fileInfo_t *fileInfo);
uint32_t CalibImageCorrection_ParseImageCorrectionDataHeader(int fd, fileInfo_t *fileInfo, CalibImageCorrection_ImageCorrectionDataHeader_t *hdr);

#endif // CALIBIMAGECORRECTIONFILE_H
