/**
 * @file CalibImageCorrectionFile.h
 * Camera image correction calibration file structure declaration.
 *
 * This file declares the camera image correction calibration file structure.
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2016 Telops Inc.
 */

#ifndef CALIBIMAGECORRECTIONFILE_H
#define CALIBIMAGECORRECTIONFILE_H

#include "IRCamFiles.h"
#include "CalibActualizationFile_v1.h"
#include "CalibImageCorrectionFile_v2.h"
#include "FileInfo.h"
#include <stdint.h>

// Calibration image correction macros versioning
#define CALIBIMAGECORRECTION_FILEMAJORVERSION      VER_MACRO(CALIBIMAGECORRECTION_FILEMAJORVERSION, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_FILEMINORVERSION      VER_MACRO(CALIBIMAGECORRECTION_FILEMINORVERSION, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_FILESUBMINORVERSION   VER_MACRO(CALIBIMAGECORRECTION_FILESUBMINORVERSION, TSICFILES_VERSION)

#define CALIBIMAGECORRECTION_IMAGECORRECTIONFILEHEADER_SIZE             VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONFILEHEADER_SIZE, TSICFILES_VERSION)

#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATAHEADER_SIZE             VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATAHEADER_SIZE, TSICFILES_VERSION)

#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_SIZE                   VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_SIZE, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_MASK         VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_MASK, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SHIFT        VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SHIFT, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SIGNPOS      VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_DELTABETA_SIGNPOS, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_MASK       VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_MASK, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_SHIFT      VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NEWBADPIXEL_SHIFT, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NOISYBADPIXEL_MASK     VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NOISYBADPIXEL_MASK, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NOISYBADPIXEL_SHIFT    VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_NOISYBADPIXEL_SHIFT, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_FLICKERBADPIXEL_MASK   VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_FLICKERBADPIXEL_MASK, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_FLICKERBADPIXEL_SHIFT  VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_FLICKERBADPIXEL_SHIFT, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_OUTLIERBADPIXEL_MASK   VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_OUTLIERBADPIXEL_MASK, TSICFILES_VERSION)
#define CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_OUTLIERBADPIXEL_SHIFT  VER_MACRO(CALIBIMAGECORRECTION_IMAGECORRECTIONDATA_OUTLIERBADPIXEL_SHIFT, TSICFILES_VERSION)

// Calibration image correction types versioning
#define CalibImageCorrection_ImageCorrectionFileHeader_t    VER_TYPE(CalibImageCorrection_ImageCorrectionFileHeader, TSICFILES_VERSION)
#define CalibImageCorrection_ImageCorrectionDataHeader_t    VER_TYPE(CalibImageCorrection_ImageCorrectionDataHeader, TSICFILES_VERSION)

// Calibration image correction default value versioning
#define CalibImageCorrection_ImageCorrectionFileHeader_default    VER_DEFAULT(CalibImageCorrection_ImageCorrectionFileHeader, TSICFILES_VERSION)
#define CalibImageCorrection_ImageCorrectionDataHeader_default    VER_DEFAULT(CalibImageCorrection_ImageCorrectionDataHeader, TSICFILES_VERSION)

// Calibration image correction function versioning
#define CalibImageCorrection_WriteImageCorrectionFileHeader    VER_FUN(CalibImageCorrection_WriteImageCorrectionFileHeader, TSICFILES_VERSION)
#define CalibImageCorrection_PrintImageCorrectionFileHeader    VER_FUN(CalibImageCorrection_PrintImageCorrectionFileHeader, TSICFILES_VERSION)
#define CalibImageCorrection_WriteImageCorrectionDataHeader    VER_FUN(CalibImageCorrection_WriteImageCorrectionDataHeader, TSICFILES_VERSION)
#define CalibImageCorrection_PrintImageCorrectionDataHeader    VER_FUN(CalibImageCorrection_PrintImageCorrectionDataHeader, TSICFILES_VERSION)
#define CalibImageCorrection_WriteImageCorrectionData          VER_FUN(CalibImageCorrection_WriteImageCorrectionData, TSICFILES_VERSION)

uint32_t CalibImageCorrection_ParseImageCorrectionFileHeader(int fd, CalibImageCorrection_ImageCorrectionFileHeader_t *hdr, fileInfo_t *fileInfo);
uint32_t CalibImageCorrection_ParseImageCorrectionDataHeader(int fd, fileInfo_t *fileInfo, CalibImageCorrection_ImageCorrectionDataHeader_t *hdr);

#endif // CALIBIMAGECORRECTIONFILE_H
