/**
 * @file CalibBlockFile.h
 * Camera calibration block file structure declaration.
 *
 * This file declares the camera calibration block file structure.
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2014 Telops Inc.
 */

#ifndef CALIBBLOCKFILE_H
#define CALIBBLOCKFILE_H

#include "CalibFiles.h"
#include "CalibBlockFile_v1.h"
#include "CalibBlockFile_v2.h"
#include "FileInfo.h"
#include <stdint.h>

// Calibration block macros versioning
#define CALIBBLOCK_FILEMAJORVERSION          VER_MACRO(CALIBBLOCK_FILEMAJORVERSION, CALIBFILES_VERSION)
#define CALIBBLOCK_FILEMINORVERSION          VER_MACRO(CALIBBLOCK_FILEMINORVERSION, CALIBFILES_VERSION)
#define CALIBBLOCK_FILESUBMINORVERSION       VER_MACRO(CALIBBLOCK_FILESUBMINORVERSION, CALIBFILES_VERSION)

#define CALIBBLOCK_CALIBBLOCKFILEHEADER_SIZE VER_MACRO(CALIBBLOCK_CALIBBLOCKFILEHEADER_SIZE, CALIBFILES_VERSION)

#define CALIBBLOCK_PIXELDATAHEADER_SIZE      VER_MACRO(CALIBBLOCK_PIXELDATAHEADER_SIZE, CALIBFILES_VERSION)

#define CALIBBLOCK_PIXELDATA_OFFSET_MASK     VER_MACRO(CALIBBLOCK_PIXELDATA_OFFSET_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_OFFSET_SHIFT    VER_MACRO(CALIBBLOCK_PIXELDATA_OFFSET_SHIFT, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_RANGE_MASK      VER_MACRO(CALIBBLOCK_PIXELDATA_RANGE_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_RANGE_SHIFT     VER_MACRO(CALIBBLOCK_PIXELDATA_RANGE_SHIFT, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_LUTNLINDEX      VER_MACRO(CALIBBLOCK_PIXELDATA_LUTNLINDEX, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_LUTNLINDEX      VER_MACRO(CALIBBLOCK_PIXELDATA_LUTNLINDEX, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_KAPPA_MASK      VER_MACRO(CALIBBLOCK_PIXELDATA_KAPPA_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_KAPPA_SHIFT     VER_MACRO(CALIBBLOCK_PIXELDATA_KAPPA_SHIFT, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_BETA0_MASK      VER_MACRO(CALIBBLOCK_PIXELDATA_BETA0_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_BETA0_SHIFT     VER_MACRO(CALIBBLOCK_PIXELDATA_BETA0_SHIFT, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_BETA0_SIGNPOS   VER_MACRO(CALIBBLOCK_PIXELDATA_BETA0_SIGNPOS, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_ALPHA_MASK      VER_MACRO(CALIBBLOCK_PIXELDATA_ALPHA_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_ALPHA_SHIFT     VER_MACRO(CALIBBLOCK_PIXELDATA_ALPHA_SHIFT, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_BADPIXEL_MASK   VER_MACRO(CALIBBLOCK_PIXELDATA_BADPIXEL_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_PIXELDATA_BADPIXEL_SHIFT  VER_MACRO(CALIBBLOCK_PIXELDATA_BADPIXEL_SHIFT, CALIBFILES_VERSION)

#define CALIBBLOCK_MAXTKDATAHEADER_SIZE      VER_MACRO(CALIBBLOCK_MAXTKDATAHEADER_SIZE, CALIBFILES_VERSION)

#define CALIBBLOCK_LUTNLDATAHEADER_SIZE      VER_MACRO(CALIBBLOCK_LUTNLDATAHEADER_SIZE, CALIBFILES_VERSION)

#define CALIBBLOCK_LUTNLDATA_SIZE            VER_MACRO(CALIBBLOCK_LUTNLDATA_SIZE, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTNLDATA_M_MASK          VER_MACRO(CALIBBLOCK_LUTNLDATA_M_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTNLDATA_M_SHIFT         VER_MACRO(CALIBBLOCK_LUTNLDATA_M_SHIFT, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTNLDATA_B_MASK          VER_MACRO(CALIBBLOCK_LUTNLDATA_B_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTNLDATA_B_SHIFT         VER_MACRO(CALIBBLOCK_LUTNLDATA_B_SHIFT, CALIBFILES_VERSION)

#define CALIBBLOCK_LUTRQDATAHEADER_SIZE      VER_MACRO(CALIBBLOCK_LUTRQDATAHEADER_SIZE, CALIBFILES_VERSION)

#define CALIBBLOCK_LUTRQDATA_SIZE            VER_MACRO(CALIBBLOCK_LUTRQDATA_SIZE, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTRQDATA_M_MASK          VER_MACRO(CALIBBLOCK_LUTRQDATA_M_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTRQDATA_M_SHIFT         VER_MACRO(CALIBBLOCK_LUTRQDATA_M_SHIFT, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTRQDATA_B_MASK          VER_MACRO(CALIBBLOCK_LUTRQDATA_B_MASK, CALIBFILES_VERSION)
#define CALIBBLOCK_LUTRQDATA_B_SHIFT         VER_MACRO(CALIBBLOCK_LUTRQDATA_B_SHIFT, CALIBFILES_VERSION)

// Calibration block types versioning
#define CalibBlock_BlockFileHeader_t         VER_TYPE(CalibBlock_BlockFileHeader, CALIBFILES_VERSION)
#define CalibBlock_PixelDataHeader_t         VER_TYPE(CalibBlock_PixelDataHeader, CALIBFILES_VERSION)
#define CalibBlock_PixelData_t               VER_TYPE(CalibBlock_PixelData, CALIBFILES_VERSION)
#define CalibBlock_MaxTKDataHeader_t         VER_TYPE(CalibBlock_MaxTKDataHeader, CALIBFILES_VERSION)
#define CalibBlock_LUTNLDataHeader_t         VER_TYPE(CalibBlock_LUTNLDataHeader, CALIBFILES_VERSION)
#define CalibBlock_LUTNLData_t               VER_TYPE(CalibBlock_LUTNLData, CALIBFILES_VERSION)
#define CalibBlock_LUTRQDataHeader_t         VER_TYPE(CalibBlock_LUTRQDataHeader, CALIBFILES_VERSION)
#define CalibBlock_LUTRQData_t               VER_TYPE(CalibBlock_LUTRQData, CALIBFILES_VERSION)

#define CALIBBLOCK_EXP_TIME_TO_US   ((float)1e-2)

/**
 * RadiometricQuantityType enumeration values
 */
enum radiometricQuantityTypeEnum {
   RQT_RT = 0,
   RQT_IBR = 1,
   RQT_IBI = 4
};

/**
 * RadiometricQuantityType enumeration values data type
 */
typedef enum radiometricQuantityTypeEnum radiometricQuantityType_t;

/**
 * CalibrationType enumeration values
 */
enum calibrationTypeEnum {
   CALT_NL = 0,
   CALT_ICU = 1,
   CALT_MULTIPOINT = 2,
   CALT_TELOPS = 3
};

/**
 * CalibrationType enumeration values data type
 */
typedef enum calibrationTypeEnum calibrationType_t;


// Calibration block function versioning
#define CalibBlock_WriteBlockFileHeader      VER_FUN(CalibBlock_WriteBlockFileHeader, CALIBFILES_VERSION)
#define CalibBlock_WritePixelDataHeader      VER_FUN(CalibBlock_WritePixelDataHeader, CALIBFILES_VERSION)
#define CalibBlock_WritePixelData            VER_FUN(CalibBlock_WritePixelData, CALIBFILES_VERSION)
#define CalibBlock_WriteMaxTKDataHeader      VER_FUN(CalibBlock_WriteMaxTKDataHeader, CALIBFILES_VERSION)
#define CalibBlock_WriteLUTNLDataHeader      VER_FUN(CalibBlock_WriteLUTNLDataHeader, CALIBFILES_VERSION)
#define CalibBlock_WriteLUTNLData            VER_FUN(CalibBlock_WriteLUTNLData, CALIBFILES_VERSION)
#define CalibBlock_WriteLUTRQDataHeader      VER_FUN(CalibBlock_WriteLUTRQDataHeader, CALIBFILES_VERSION)
#define CalibBlock_WriteLUTRQData            VER_FUN(CalibBlock_WriteLUTRQData, CALIBFILES_VERSION)

uint32_t CalibBlock_ParseBlockFileHeader(int fd, CalibBlock_BlockFileHeader_t *hdr, fileInfo_t *fileInfo);
uint32_t CalibBlock_ParsePixelDataHeader(int fd, fileInfo_t *fileInfo, CalibBlock_PixelDataHeader_t *hdr);
uint32_t CalibBlock_ParseMaxTKDataHeader(int fd, fileInfo_t *fileInfo, CalibBlock_MaxTKDataHeader_t *hdr);
uint32_t CalibBlock_ParseLUTNLDataHeader(int fd, fileInfo_t *fileInfo, CalibBlock_LUTNLDataHeader_t *hdr);
uint32_t CalibBlock_ParseLUTRQDataHeader(int fd, fileInfo_t *fileInfo, CalibBlock_LUTRQDataHeader_t *hdr);

#endif // CALIBBLOCKFILE_H
