/**
 * @file tel2000_param.h
 * Tel2000 axi port address map.
 *
 * This file declares the address of every axi lite port.
 * This is automaticly generated by tel_extract_param.tcl
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2014 Telops Inc.
 */
 
#ifndef TEL2000_PARAM_H
#define TEL2000_PARAM_H
 
 /**
* Clock declaration
*/
#define CLK_100_FREQ_HZ 100000000
#define CLK_160_FREQ_HZ 100000000
#define CLK_20_FREQ_HZ 100000000
#define CLK_200_FREQ_HZ 100000000
#define CLK_50_FREQ_HZ 100000000
#define CLK_80_FREQ_HZ 100000000

/**
 * AXI PORT declaration
 */
/* Definitions for peripheral TEL_ADC_READOUT_CTRL */
#define TEL_PAR_TEL_ADC_READOUT_CTRL_BASEADDR 0x44B50000
#define TEL_PAR_TEL_ADC_READOUT_CTRL_HIGHADDR 0x44B50FFF 

/* Definitions for peripheral TEL_AEC_CTRL */
#define TEL_PAR_TEL_AEC_CTRL_BASEADDR 0x44A00000
#define TEL_PAR_TEL_AEC_CTRL_HIGHADDR 0x44A00FFF 

/* Definitions for peripheral TEL_BUFFERING_CTRL */
#define TEL_PAR_TEL_BUFFERING_CTRL_BASEADDR 0x44A40000
#define TEL_PAR_TEL_BUFFERING_CTRL_HIGHADDR 0x44A4FFFF 

/* Definitions for peripheral TEL_BUFTABLE */
#define TEL_PAR_TEL_BUFTABLE_BASEADDR 0x44B30000
#define TEL_PAR_TEL_BUFTABLE_HIGHADDR 0x44B3FFFF 

/* Definitions for peripheral TEL_CALIB_RAM */
#define TEL_PAR_TEL_CALIB_RAM_BASEADDR 0x44A10000
#define TEL_PAR_TEL_CALIB_RAM_HIGHADDR 0x44A10FFF 

/* Definitions for peripheral TEL_CAL_CTRL */
#define TEL_PAR_TEL_CAL_CTRL_BASEADDR 0x44A20000
#define TEL_PAR_TEL_CAL_CTRL_HIGHADDR 0x44A23FFF 

/* Definitions for peripheral TEL_EHDRI_CTRL */
#define TEL_PAR_TEL_EHDRI_CTRL_BASEADDR 0x44B40000
#define TEL_PAR_TEL_EHDRI_CTRL_HIGHADDR 0x44B40FFF 

/* Definitions for peripheral TEL_EXPTIM_CTRL */
#define TEL_PAR_TEL_EXPTIM_CTRL_BASEADDR 0x44A30000
#define TEL_PAR_TEL_EXPTIM_CTRL_HIGHADDR 0x44A30FFF 

/* Definitions for peripheral TEL_FAN_CTRL */
#define TEL_PAR_TEL_FAN_CTRL_BASEADDR 0x44AA0000
#define TEL_PAR_TEL_FAN_CTRL_HIGHADDR 0x44AA0FFF 

/* Definitions for peripheral TEL_FLASH_INTF */
#define TEL_PAR_TEL_FLASH_INTF_BASEADDR 0x44B10000
#define TEL_PAR_TEL_FLASH_INTF_HIGHADDR 0x44B13FFF 

/* Definitions for peripheral TEL_FPA_CTRL */
#define TEL_PAR_TEL_FPA_CTRL_BASEADDR 0x44A50000
#define TEL_PAR_TEL_FPA_CTRL_HIGHADDR 0x44A50FFF 

/* Definitions for peripheral TEL_HEADER_CTRL */
#define TEL_PAR_TEL_HEADER_CTRL_BASEADDR 0x44A60000
#define TEL_PAR_TEL_HEADER_CTRL_HIGHADDR 0x44A60FFF 

/* Definitions for peripheral TEL_ICU_CTRL */
#define TEL_PAR_TEL_ICU_CTRL_BASEADDR 0x44B20000
#define TEL_PAR_TEL_ICU_CTRL_HIGHADDR 0x44B20FFF 

/* Definitions for peripheral TEL_IRIG_CTRL */
#define TEL_PAR_TEL_IRIG_CTRL_BASEADDR 0x44AC0000
#define TEL_PAR_TEL_IRIG_CTRL_HIGHADDR 0x44AC0FFF 

/* Definitions for peripheral TEL_MGT_CTRL */
#define TEL_PAR_TEL_MGT_CTRL_BASEADDR 0x44AB0000
#define TEL_PAR_TEL_MGT_CTRL_HIGHADDR 0x44AB0FFF 

/* Definitions for peripheral TEL_NLC_LUT */
#define TEL_PAR_TEL_NLC_LUT_BASEADDR 0x44AF0000
#define TEL_PAR_TEL_NLC_LUT_HIGHADDR 0x44AF3FFF 

/* Definitions for peripheral TEL_RQC_LUT */
#define TEL_PAR_TEL_RQC_LUT_BASEADDR 0x44AE0000
#define TEL_PAR_TEL_RQC_LUT_HIGHADDR 0x44AE7FFF 

/* Definitions for peripheral TEL_SFW_CTRL */
#define TEL_PAR_TEL_SFW_CTRL_BASEADDR 0x44A70000
#define TEL_PAR_TEL_SFW_CTRL_HIGHADDR 0x44A70FFF 

/* Definitions for peripheral TEL_TRIGGER_CTRL */
#define TEL_PAR_TEL_TRIGGER_CTRL_BASEADDR 0x44A80000
#define TEL_PAR_TEL_TRIGGER_CTRL_HIGHADDR 0x44A80FFF 

/* Definitions for peripheral TEL_USART_CTRL */
#define TEL_PAR_TEL_USART_CTRL_BASEADDR 0x44AD0000
#define TEL_PAR_TEL_USART_CTRL_HIGHADDR 0x44AD1FFF 

#endif // TEL2000_PARAM_H
