# Author : JBO
# DATE : 13 Fev 2014

# This script extract the data from the core.bd addresse map and write it in the file tel2000_param.h

# It assume segment have been name in the Adresse editor to start with "TEL_*"
# This could be done(in adress editor) by clicking on the segment in the cell column
# and changing the name in the adress segment properties windows

open_bd_design [get_files *core.bd]

#Extract the clock information
set clkName [get_property NAME [get_bd_ports -filter {TYPE == clk && DIR == O}]]
set clkFreq [get_property CONFIG.FREQ_HZ [get_bd_ports -filter {TYPE == clk && DIR == O}]]

#open a file to write to
set filename  "d:/telops/fir-00251-Proc/src/sw/tel2000_param.h"
set fd1 [open $filename "w"]

#Start to write the First line of the header file (DOXYGEN)
puts $fd1 "/**
 * @file tel2000_param.h
 * Tel2000 axi port address map.
 *
 * This file declares the address of every axi lite port.
 * This is automaticly generated by tel_extract_param.tcl
 *
 * \$Rev\$
 * \$Author\$
 * \$Date\$
 * \$Id\$
 * \$URL\$
 *
 * (c) Copyright 2014 Telops Inc.
 */
 
#ifndef TEL2000_PARAM_H
#define TEL2000_PARAM_H
 
 /**
* Clock declaration
*/"

#enter a loop that write all the information
set i 0
foreach j $clkName {
   puts $fd1 "#define [string toupper [lindex $clkName $i]]_FREQ_HZ [lindex $clkFreq $i]"
   incr i
}
puts $fd1 ""
puts $fd1 "#endif // TEL2000_PARAM_H"

#close file 
close $fd1
