set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[31]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[0]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[1]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[2]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[3]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[4]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[5]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[6]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[7]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[8]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[9]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[10]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[11]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[12]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[13]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[14]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[15]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[16]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[17]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[18]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[19]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[20]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[21]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[22]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[23]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[24]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[25]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[26]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[27]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[28]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[29]}]
set_property MARK_DEBUG false [get_nets {ACQ/BUF_MNG/U13/cnt[30]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[8]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[9]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[10]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[11]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[12]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[13]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[14]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/cfg_byte_total[15]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[8]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[9]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[10]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[11]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[12]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[13]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[14]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[15]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[16]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[17]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[18]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[19]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[20]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[21]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[22]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[23]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[24]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[25]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[26]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[27]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[28]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[29]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[30]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/fpa_temp_reg[31]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_dcnt[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/resp_err[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[8]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[9]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[10]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[11]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[12]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[13]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[14]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/sub_cmd_byte_cnt[15]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb_id[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_lsb[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb_id[0]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[7]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[6]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[5]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[4]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[3]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[2]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[1]}]
set_property MARK_DEBUG true [get_nets {FPA/U5/U2/temp_msb[0]}]
set_property MARK_DEBUG true [get_nets FPA/U5/U2/cmd_eof_latch]
set_property MARK_DEBUG true [get_nets FPA/U5/U2/cmd_resp_done]
set_property MARK_DEBUG true [get_nets FPA/U5/U2/serial_cmd_failure]
set_property MARK_DEBUG true [get_nets FPA/U5/U2/timeout_reached]
set_property MARK_DEBUG true [get_nets FPA/U5/U2/SERIAL_FATAL_ERR]
create_debug_core u_ila_0 labtools_ila_v3
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK100]]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {FPA/U5/U2/cfg_byte_total[0]} {FPA/U5/U2/cfg_byte_total[1]} {FPA/U5/U2/cfg_byte_total[2]} {FPA/U5/U2/cfg_byte_total[3]} {FPA/U5/U2/cfg_byte_total[4]} {FPA/U5/U2/cfg_byte_total[5]} {FPA/U5/U2/cfg_byte_total[6]} {FPA/U5/U2/cfg_byte_total[7]} {FPA/U5/U2/cfg_byte_total[8]} {FPA/U5/U2/cfg_byte_total[9]} {FPA/U5/U2/cfg_byte_total[10]} {FPA/U5/U2/cfg_byte_total[11]} {FPA/U5/U2/cfg_byte_total[12]} {FPA/U5/U2/cfg_byte_total[13]} {FPA/U5/U2/cfg_byte_total[14]} {FPA/U5/U2/cfg_byte_total[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {FPA/U5/U2/fpa_temp_reg[0]} {FPA/U5/U2/fpa_temp_reg[1]} {FPA/U5/U2/fpa_temp_reg[2]} {FPA/U5/U2/fpa_temp_reg[3]} {FPA/U5/U2/fpa_temp_reg[4]} {FPA/U5/U2/fpa_temp_reg[5]} {FPA/U5/U2/fpa_temp_reg[6]} {FPA/U5/U2/fpa_temp_reg[7]} {FPA/U5/U2/fpa_temp_reg[8]} {FPA/U5/U2/fpa_temp_reg[9]} {FPA/U5/U2/fpa_temp_reg[10]} {FPA/U5/U2/fpa_temp_reg[11]} {FPA/U5/U2/fpa_temp_reg[12]} {FPA/U5/U2/fpa_temp_reg[13]} {FPA/U5/U2/fpa_temp_reg[14]} {FPA/U5/U2/fpa_temp_reg[15]} {FPA/U5/U2/fpa_temp_reg[16]} {FPA/U5/U2/fpa_temp_reg[17]} {FPA/U5/U2/fpa_temp_reg[18]} {FPA/U5/U2/fpa_temp_reg[19]} {FPA/U5/U2/fpa_temp_reg[20]} {FPA/U5/U2/fpa_temp_reg[21]} {FPA/U5/U2/fpa_temp_reg[22]} {FPA/U5/U2/fpa_temp_reg[23]} {FPA/U5/U2/fpa_temp_reg[24]} {FPA/U5/U2/fpa_temp_reg[25]} {FPA/U5/U2/fpa_temp_reg[26]} {FPA/U5/U2/fpa_temp_reg[27]} {FPA/U5/U2/fpa_temp_reg[28]} {FPA/U5/U2/fpa_temp_reg[29]} {FPA/U5/U2/fpa_temp_reg[30]} {FPA/U5/U2/fpa_temp_reg[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {FPA/U5/U2/resp_dcnt[0]} {FPA/U5/U2/resp_dcnt[1]} {FPA/U5/U2/resp_dcnt[2]} {FPA/U5/U2/resp_dcnt[3]} {FPA/U5/U2/resp_dcnt[4]} {FPA/U5/U2/resp_dcnt[5]} {FPA/U5/U2/resp_dcnt[6]} {FPA/U5/U2/resp_dcnt[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {FPA/U5/U2/resp_err[0]} {FPA/U5/U2/resp_err[1]} {FPA/U5/U2/resp_err[2]} {FPA/U5/U2/resp_err[3]} {FPA/U5/U2/resp_err[4]} {FPA/U5/U2/resp_err[5]} {FPA/U5/U2/resp_err[6]} {FPA/U5/U2/resp_err[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {FPA/U5/U2/sub_cmd_byte_cnt[0]} {FPA/U5/U2/sub_cmd_byte_cnt[1]} {FPA/U5/U2/sub_cmd_byte_cnt[2]} {FPA/U5/U2/sub_cmd_byte_cnt[3]} {FPA/U5/U2/sub_cmd_byte_cnt[4]} {FPA/U5/U2/sub_cmd_byte_cnt[5]} {FPA/U5/U2/sub_cmd_byte_cnt[6]} {FPA/U5/U2/sub_cmd_byte_cnt[7]} {FPA/U5/U2/sub_cmd_byte_cnt[8]} {FPA/U5/U2/sub_cmd_byte_cnt[9]} {FPA/U5/U2/sub_cmd_byte_cnt[10]} {FPA/U5/U2/sub_cmd_byte_cnt[11]} {FPA/U5/U2/sub_cmd_byte_cnt[12]} {FPA/U5/U2/sub_cmd_byte_cnt[13]} {FPA/U5/U2/sub_cmd_byte_cnt[14]} {FPA/U5/U2/sub_cmd_byte_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {FPA/U5/U2/temp_lsb[0]} {FPA/U5/U2/temp_lsb[1]} {FPA/U5/U2/temp_lsb[2]} {FPA/U5/U2/temp_lsb[3]} {FPA/U5/U2/temp_lsb[4]} {FPA/U5/U2/temp_lsb[5]} {FPA/U5/U2/temp_lsb[6]} {FPA/U5/U2/temp_lsb[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {FPA/U5/U2/temp_lsb_id[0]} {FPA/U5/U2/temp_lsb_id[1]} {FPA/U5/U2/temp_lsb_id[2]} {FPA/U5/U2/temp_lsb_id[3]} {FPA/U5/U2/temp_lsb_id[4]} {FPA/U5/U2/temp_lsb_id[5]} {FPA/U5/U2/temp_lsb_id[6]} {FPA/U5/U2/temp_lsb_id[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {FPA/U5/U2/temp_msb[0]} {FPA/U5/U2/temp_msb[1]} {FPA/U5/U2/temp_msb[2]} {FPA/U5/U2/temp_msb[3]} {FPA/U5/U2/temp_msb[4]} {FPA/U5/U2/temp_msb[5]} {FPA/U5/U2/temp_msb[6]} {FPA/U5/U2/temp_msb[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {FPA/U5/U2/temp_msb_id[0]} {FPA/U5/U2/temp_msb_id[1]} {FPA/U5/U2/temp_msb_id[2]} {FPA/U5/U2/temp_msb_id[3]} {FPA/U5/U2/temp_msb_id[4]} {FPA/U5/U2/temp_msb_id[5]} {FPA/U5/U2/temp_msb_id[6]} {FPA/U5/U2/temp_msb_id[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list FPA/U5/U2/cmd_eof_latch]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list FPA/U5/U2/cmd_resp_done]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list FPA/U5/U2/serial_cmd_failure]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list FPA/U5/U2/SERIAL_FATAL_ERR]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list FPA/U5/U2/timeout_reached]]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
