#
# Vivado (TM) v2016.3 (64-bit)
#
# AXIL_LUT_tb.tcl: Tcl script for re-creating project 'AXIL_LUT_tb'
#
# Generated by Vivado on Fri Jun 17 11:44:23 -0400 2022
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (AXIL_LUT_tb.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/Telops/FIR-00251-Proc/IP/160/tdp_ram_w32_d8192/tdp_ram_w32_d8192.xci"
#    "D:/Telops/FIR-00251-Proc/IP/160/tdp_ram_w32_d32768/tdp_ram_w32_d32768.xci"
#    "D:/Telops/FIR-00251-Proc/IP/160/tdp_ram_w32_d16384/tdp_ram_w32_d16384.xci"
#    "D:/Telops/FIR-00251-Common/VHDL/tel2000pkg.vhd"
#    "D:/Telops/Common_HDL/Utilities/sync_reset.vhd"
#    "D:/Telops/FIR-00251-Common/VHDL/Utilities/axil32_to_native.vhd"
#    "D:/Telops/FIR-00251-Common/VHDL/Lut/LUT_native_switch.vhd"
#    "D:/Telops/FIR-00251-Common/VHDL/Ram/tdp_ram_w32.vhd"
#    "D:/Telops/FIR-00251-Proc/src/Calibration/Sim_Vivado/AXIL_LUT_tb.vhd"
#    "D:/Telops/FIR-00251-Proc/src/Calibration/Sim_Vivado/AXIL_LUT_tb_behav.wcfg"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "AXIL_LUT_tb.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/AXIL_LUT_tb"]"

# Create project
create_project AXIL_LUT_tb ./AXIL_LUT_tb -part xc7k160tfbg676-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects AXIL_LUT_tb]
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "read write" $obj
set_property "ip_output_repo" "D:/Telops/FIR-00251-Proc/src/Calibration/Sim_Vivado/AXIL_LUT_tb/AXIL_LUT_tb.cache/ip" $obj
set_property "part" "xc7k160tfbg676-1" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj
set_property "xpm_libraries" "XPM_MEMORY" $obj
set_property "xsim.array_display_limit" "64" $obj
set_property "xsim.trace_limit" "65536" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../IP/160/tdp_ram_w32_d8192/tdp_ram_w32_d8192.xci"]"\
 "[file normalize "$origin_dir/../../../IP/160/tdp_ram_w32_d32768/tdp_ram_w32_d32768.xci"]"\
 "[file normalize "$origin_dir/../../../IP/160/tdp_ram_w32_d16384/tdp_ram_w32_d16384.xci"]"\
 "[file normalize "$origin_dir/../../../../FIR-00251-Common/VHDL/tel2000pkg.vhd"]"\
 "[file normalize "$origin_dir/../../../../Common_HDL/Utilities/sync_reset.vhd"]"\
 "[file normalize "$origin_dir/../../../../FIR-00251-Common/VHDL/Utilities/axil32_to_native.vhd"]"\
 "[file normalize "$origin_dir/../../../../FIR-00251-Common/VHDL/Lut/LUT_native_switch.vhd"]"\
 "[file normalize "$origin_dir/../../../../FIR-00251-Common/VHDL/Ram/tdp_ram_w32.vhd"]"\
 "[file normalize "$origin_dir/AXIL_LUT_tb.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../../../FIR-00251-Common/VHDL/tel2000pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../../Common_HDL/Utilities/sync_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../../FIR-00251-Common/VHDL/Utilities/axil32_to_native.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../../FIR-00251-Common/VHDL/Lut/LUT_native_switch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../../../../FIR-00251-Common/VHDL/Ram/tdp_ram_w32.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/AXIL_LUT_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "AXIL_LUT_tb" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/AXIL_LUT_tb_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "AXIL_LUT_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.view" "D:/Telops/FIR-00251-Proc/src/Calibration/Sim_Vivado/AXIL_LUT_tb/AXIL_LUT_tb_behav.wcfg D:/Telops/FIR-00251-Proc/src/Calibration/Sim_Vivado/AXIL_LUT_tb_behav.wcfg" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k160tfbg676-1 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7k160tfbg676-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k160tfbg676-1 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7k160tfbg676-1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:AXIL_LUT_tb"
