set_property MARK_DEBUG true [get_nets U3/U5/U4/PROG_DONE]
set_property MARK_DEBUG true [get_nets U3/U5/U4/readout_i]
set_property MARK_DEBUG true [get_nets U3/U5/U4/PROG_EN]
set_property MARK_DEBUG true [get_nets U3/U5/U4/PROG_RQST]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/hw_seq_fsm[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/prog_ctrl_fsm[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/hw_seq_fsm[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/hw_seq_fsm[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/prog_ctrl_fsm[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/prog_ctrl_fsm[1]}]
set_property MARK_DEBUG true [get_nets U3/U5/U4/valid_prog_rqst]
set_property MARK_DEBUG true [get_nets U3/U5/U4/HW_DRIVER_EN]
set_property MARK_DEBUG true [get_nets U3/U5/U4/fpa_intf_cfg_up2date]
set_property MARK_DEBUG true [get_nets U3/U5/U4/run_fpa_prog_client]
set_property MARK_DEBUG true [get_nets U3/U5/U4/update_fpa_part_only]
set_property MARK_DEBUG true [get_nets U3/U5/U4/update_fpa_cfg]
set_property MARK_DEBUG true [get_nets U3/U5/U4/fpa_client_done]
set_property MARK_DEBUG true [get_nets U3/U5/U4/fpa_first_cfg_done]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[24]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[15]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[12]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[35]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[36]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[27]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[21]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[18]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[38]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[32]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[29]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[9]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[23]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[10]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[30]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[33]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[39]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[11]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[14]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[17]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[20]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[34]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[17]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[30]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[31]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[26]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[15]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[28]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[33]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[22]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[16]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[20]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[35]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[37]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[9]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[11]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[13]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[14]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[19]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[22]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[23]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[25]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[26]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[29]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[31]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[32]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[38]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[8]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[10]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[12]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[13]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[16]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[18]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[19]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[21]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[24]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[25]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[27]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[28]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[34]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[36]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[37]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[39]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[8]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[3]}]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/fpa_error_i]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/new_cfg_num_pending]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/new_cfg_pending]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/SPI_DONE]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list U3/U26/U2/U2/inst/mclk_source]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {U3/U5/U4/hw_seq_fsm[0]} {U3/U5/U4/hw_seq_fsm[1]} {U3/U5/U4/hw_seq_fsm[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {U3/U5/U4/prog_ctrl_fsm[0]} {U3/U5/U4/prog_ctrl_fsm[1]} {U3/U5/U4/prog_ctrl_fsm[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {U3/U5/U2/U3/new_cfg_num[0]} {U3/U5/U2/U3/new_cfg_num[1]} {U3/U5/U2/U3/new_cfg_num[2]} {U3/U5/U2/U3/new_cfg_num[3]} {U3/U5/U2/U3/new_cfg_num[4]} {U3/U5/U2/U3/new_cfg_num[5]} {U3/U5/U2/U3/new_cfg_num[6]} {U3/U5/U2/U3/new_cfg_num[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 40 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {U3/U5/U2/U3/new_cfg[0]} {U3/U5/U2/U3/new_cfg[1]} {U3/U5/U2/U3/new_cfg[2]} {U3/U5/U2/U3/new_cfg[3]} {U3/U5/U2/U3/new_cfg[4]} {U3/U5/U2/U3/new_cfg[5]} {U3/U5/U2/U3/new_cfg[6]} {U3/U5/U2/U3/new_cfg[7]} {U3/U5/U2/U3/new_cfg[8]} {U3/U5/U2/U3/new_cfg[9]} {U3/U5/U2/U3/new_cfg[10]} {U3/U5/U2/U3/new_cfg[11]} {U3/U5/U2/U3/new_cfg[12]} {U3/U5/U2/U3/new_cfg[13]} {U3/U5/U2/U3/new_cfg[14]} {U3/U5/U2/U3/new_cfg[15]} {U3/U5/U2/U3/new_cfg[16]} {U3/U5/U2/U3/new_cfg[17]} {U3/U5/U2/U3/new_cfg[18]} {U3/U5/U2/U3/new_cfg[19]} {U3/U5/U2/U3/new_cfg[20]} {U3/U5/U2/U3/new_cfg[21]} {U3/U5/U2/U3/new_cfg[22]} {U3/U5/U2/U3/new_cfg[23]} {U3/U5/U2/U3/new_cfg[24]} {U3/U5/U2/U3/new_cfg[25]} {U3/U5/U2/U3/new_cfg[26]} {U3/U5/U2/U3/new_cfg[27]} {U3/U5/U2/U3/new_cfg[28]} {U3/U5/U2/U3/new_cfg[29]} {U3/U5/U2/U3/new_cfg[30]} {U3/U5/U2/U3/new_cfg[31]} {U3/U5/U2/U3/new_cfg[32]} {U3/U5/U2/U3/new_cfg[33]} {U3/U5/U2/U3/new_cfg[34]} {U3/U5/U2/U3/new_cfg[35]} {U3/U5/U2/U3/new_cfg[36]} {U3/U5/U2/U3/new_cfg[37]} {U3/U5/U2/U3/new_cfg[38]} {U3/U5/U2/U3/new_cfg[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 40 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {U3/U5/U2/U3/present_cfg[0]} {U3/U5/U2/U3/present_cfg[1]} {U3/U5/U2/U3/present_cfg[2]} {U3/U5/U2/U3/present_cfg[3]} {U3/U5/U2/U3/present_cfg[4]} {U3/U5/U2/U3/present_cfg[5]} {U3/U5/U2/U3/present_cfg[6]} {U3/U5/U2/U3/present_cfg[7]} {U3/U5/U2/U3/present_cfg[8]} {U3/U5/U2/U3/present_cfg[9]} {U3/U5/U2/U3/present_cfg[10]} {U3/U5/U2/U3/present_cfg[11]} {U3/U5/U2/U3/present_cfg[12]} {U3/U5/U2/U3/present_cfg[13]} {U3/U5/U2/U3/present_cfg[14]} {U3/U5/U2/U3/present_cfg[15]} {U3/U5/U2/U3/present_cfg[16]} {U3/U5/U2/U3/present_cfg[17]} {U3/U5/U2/U3/present_cfg[18]} {U3/U5/U2/U3/present_cfg[19]} {U3/U5/U2/U3/present_cfg[20]} {U3/U5/U2/U3/present_cfg[21]} {U3/U5/U2/U3/present_cfg[22]} {U3/U5/U2/U3/present_cfg[23]} {U3/U5/U2/U3/present_cfg[24]} {U3/U5/U2/U3/present_cfg[25]} {U3/U5/U2/U3/present_cfg[26]} {U3/U5/U2/U3/present_cfg[27]} {U3/U5/U2/U3/present_cfg[28]} {U3/U5/U2/U3/present_cfg[29]} {U3/U5/U2/U3/present_cfg[30]} {U3/U5/U2/U3/present_cfg[31]} {U3/U5/U2/U3/present_cfg[32]} {U3/U5/U2/U3/present_cfg[33]} {U3/U5/U2/U3/present_cfg[34]} {U3/U5/U2/U3/present_cfg[35]} {U3/U5/U2/U3/present_cfg[36]} {U3/U5/U2/U3/present_cfg[37]} {U3/U5/U2/U3/present_cfg[38]} {U3/U5/U2/U3/present_cfg[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {U3/U5/U2/U3/present_cfg_num[0]} {U3/U5/U2/U3/present_cfg_num[1]} {U3/U5/U2/U3/present_cfg_num[2]} {U3/U5/U2/U3/present_cfg_num[3]} {U3/U5/U2/U3/present_cfg_num[4]} {U3/U5/U2/U3/present_cfg_num[5]} {U3/U5/U2/U3/present_cfg_num[6]} {U3/U5/U2/U3/present_cfg_num[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 4 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {U3/U5/U2/U3/roic_cfg_fsm[0]} {U3/U5/U2/U3/roic_cfg_fsm[1]} {U3/U5/U2/U3/roic_cfg_fsm[2]} {U3/U5/U2/U3/roic_cfg_fsm[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list U3/U5/U4/fpa_client_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list U3/U5/U2/U3/fpa_error_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list U3/U5/U4/fpa_first_cfg_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list U3/U5/U4/fpa_intf_cfg_up2date]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list U3/U5/U4/HW_DRIVER_EN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list U3/U5/U2/U3/new_cfg_num_pending]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list U3/U5/U2/U3/new_cfg_pending]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list U3/U5/U4/PROG_DONE]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list U3/U5/U4/PROG_EN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list U3/U5/U4/PROG_RQST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list U3/U5/U4/readout_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list U3/U5/U4/run_fpa_prog_client]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list U3/U5/U2/U3/SPI_DONE]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list U3/U5/U4/update_fpa_cfg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list U3/U5/U4/update_fpa_part_only]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list U3/U5/U4/valid_prog_rqst]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_DOUT]
