# Target contraints file used in release build.
# This file should remain empty.
set_property MARK_DEBUG true [get_nets U3/U5/U4/PROG_DONE]
set_property MARK_DEBUG true [get_nets U3/U5/U4/readout_i]
set_property MARK_DEBUG true [get_nets U3/U5/U4/PROG_EN]
set_property MARK_DEBUG true [get_nets U3/U5/U4/PROG_RQST]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/hw_seq_fsm[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/prog_ctrl_fsm[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/hw_seq_fsm[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/hw_seq_fsm[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/prog_ctrl_fsm[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U4/prog_ctrl_fsm[1]}]
set_property MARK_DEBUG true [get_nets U3/U5/U4/valid_prog_rqst]
set_property MARK_DEBUG true [get_nets U3/U5/U4/HW_DRIVER_EN]
set_property MARK_DEBUG true [get_nets U3/U5/U4/fpa_intf_cfg_up2date]
set_property MARK_DEBUG true [get_nets U3/U5/U4/run_fpa_prog_client]
set_property MARK_DEBUG true [get_nets U3/U5/U4/update_fpa_part_only]
set_property MARK_DEBUG true [get_nets U3/U5/U4/update_fpa_cfg]
set_property MARK_DEBUG true [get_nets U3/U5/U4/fpa_client_done]
set_property MARK_DEBUG true [get_nets U3/U5/U4/fpa_first_cfg_done]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[24]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[15]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[12]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[35]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[36]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[27]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[21]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[18]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[38]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[32]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[29]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[9]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[23]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[10]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[30]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[33]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[39]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[11]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[14]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[17]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[20]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[34]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[17]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[30]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[31]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[26]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[15]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[28]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[33]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[22]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[16]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[20]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[35]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[37]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[9]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[11]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[13]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[14]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[19]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[22]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[23]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[25]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[26]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[29]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[31]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[32]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[38]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg[8]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/new_cfg_num[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[10]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[12]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[13]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[16]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[18]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[19]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[1]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[21]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[24]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[25]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[27]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[28]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[34]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[36]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[37]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[39]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[3]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[4]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg[8]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[0]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[5]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[6]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/present_cfg_num[7]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[2]}]
set_property MARK_DEBUG true [get_nets {U3/U5/U2/U3/roic_cfg_fsm[3]}]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/fpa_error_i]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/new_cfg_num_pending]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/new_cfg_pending]
set_property MARK_DEBUG true [get_nets U3/U5/U2/U3/SPI_DONE]

set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][10]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][11]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][12]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][13]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][14]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][15]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][16]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][17]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][18]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][19]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][20]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][21]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][22]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][23]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][24]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][25]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][26]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][27]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][28]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][29]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][30]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][31]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][8]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][9]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][10]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][11]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][12]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][13]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][14]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][15]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][16]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][17]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][18]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][19]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][20]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][21]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][22]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][23]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][24]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][25]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][26]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][27]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][28]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][29]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][30]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][31]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][8]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[high_time][9]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[mode][7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][10]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][11]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][12]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][13]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][14]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][15]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][16]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][17]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][18]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][19]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][20]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][21]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][22]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][23]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][24]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][25]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][26]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][27]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][28]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][29]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][30]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][31]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][8]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[period][9]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][10]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][11]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][12]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][13]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][14]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][15]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][16]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][17]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][18]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][19]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][20]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][21]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][22]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][23]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][24]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][25]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][26]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][27]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][28]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][29]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][30]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][31]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][8]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][9]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[trig_activ][7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][10]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][11]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][12]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][13]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][14]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][15]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][16]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][17]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][18]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][19]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][20]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][21]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][22]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][23]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][24]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][25]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][26]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][27]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][28]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][29]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][30]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][31]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][8]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][9]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[10]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[11]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[12]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[13]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[14]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[15]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[16]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[17]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[18]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[19]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[20]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[21]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[22]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[23]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[24]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[25]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[26]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[27]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[28]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[29]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[30]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[31]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[3]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[4]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[5]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[6]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[7]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[8]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/internal_pulse_period_i[9]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/mode_sm[0]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/mode_sm[1]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/mode_sm[2]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[acq_window]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[force_high]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[run]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/CONFIG[seq_trigsource]}]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/fpa_trig_done]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[acq_window]}]
set_property MARK_DEBUG true [get_nets {ACQ/TRIG/U3/U2/fpa_trig_param_i[run]}]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/INTERNAL_PULSE]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/integration_detect]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/internal_pulse_cntraz_i]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/raw_pulse_i]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/seq_delay_enable_i]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/seq_enable_i]
set_property MARK_DEBUG true [get_nets ACQ/TRIG/U3/U2/seq_trig_i]
set_property MARK_DEBUG false [get_nets ACQ/TRIG/U3/U2/acq_int_last]
set_property MARK_DEBUG false [get_nets ACQ/TRIG/U3/U2/ACQ_INT]
connect_debug_port u_ila_0/probe0 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][0]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][1]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][2]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][3]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][4]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][5]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][6]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][7]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][8]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][9]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][10]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][11]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][12]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][13]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][14]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][15]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][16]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][17]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][18]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][19]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][20]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][21]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][22]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][23]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][24]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][25]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][26]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][27]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][28]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][29]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][30]} {ACQ/TRIG/U3/U2/CONFIG[fpatrig_dly][31]}]]

set_property MARK_DEBUG false [get_nets U3/U5/U4/Q]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[10]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[31]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[1]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[4]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[9]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[13]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[16]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[19]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[22]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[25]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[28]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[7]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[11]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[0]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[12]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[14]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[15]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[17]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[18]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[20]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[21]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[23]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[24]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[26]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[27]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[29]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[2]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[30]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[3]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[5]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[6]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/CONFIG[8]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/FPA_TRIG_STAT[5]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/FPA_TRIG_STAT[2]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/FPA_TRIG_STAT[1]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/FPA_TRIG_STAT[3]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/FPA_TRIG_STAT[4]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/FPA_TRIG_STAT[6]}]
set_property MARK_DEBUG false [get_nets {ACQ/TRIG/U3/U2/FPA_TRIG_STAT[7]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ACQ/BD/core_wrapper_i/core_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ACQ/TRIG/U3/U2/mode_sm[0]} {ACQ/TRIG/U3/U2/mode_sm[1]} {ACQ/TRIG/U3/U2/mode_sm[2]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list U3/U26/U2/U2/inst/mclk_source]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {U3/U5/U2/U3/roic_cfg_fsm[0]} {U3/U5/U2/U3/roic_cfg_fsm[1]} {U3/U5/U2/U3/roic_cfg_fsm[2]} {U3/U5/U2/U3/roic_cfg_fsm[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][0]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][1]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][2]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][3]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][4]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][5]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][6]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][7]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][8]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][9]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][10]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][11]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][12]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][13]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][14]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][15]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][16]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][17]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][18]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][19]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][20]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][21]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][22]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][23]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][24]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][25]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][26]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][27]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][28]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][29]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][30]} {ACQ/TRIG/U3/U2/fpa_trig_param_i[high_time][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ACQ/TRIG/U3/U2/internal_pulse_period_i[0]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[1]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[2]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[3]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[4]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[5]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[6]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[7]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[8]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[9]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[10]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[11]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[12]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[13]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[14]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[15]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[16]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[17]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[18]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[19]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[20]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[21]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[22]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[23]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[24]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[25]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[26]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[27]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[28]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[29]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[30]} {ACQ/TRIG/U3/U2/internal_pulse_period_i[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[period][0]} {ACQ/TRIG/U3/U2/CONFIG[period][1]} {ACQ/TRIG/U3/U2/CONFIG[period][2]} {ACQ/TRIG/U3/U2/CONFIG[period][3]} {ACQ/TRIG/U3/U2/CONFIG[period][4]} {ACQ/TRIG/U3/U2/CONFIG[period][5]} {ACQ/TRIG/U3/U2/CONFIG[period][6]} {ACQ/TRIG/U3/U2/CONFIG[period][7]} {ACQ/TRIG/U3/U2/CONFIG[period][8]} {ACQ/TRIG/U3/U2/CONFIG[period][9]} {ACQ/TRIG/U3/U2/CONFIG[period][10]} {ACQ/TRIG/U3/U2/CONFIG[period][11]} {ACQ/TRIG/U3/U2/CONFIG[period][12]} {ACQ/TRIG/U3/U2/CONFIG[period][13]} {ACQ/TRIG/U3/U2/CONFIG[period][14]} {ACQ/TRIG/U3/U2/CONFIG[period][15]} {ACQ/TRIG/U3/U2/CONFIG[period][16]} {ACQ/TRIG/U3/U2/CONFIG[period][17]} {ACQ/TRIG/U3/U2/CONFIG[period][18]} {ACQ/TRIG/U3/U2/CONFIG[period][19]} {ACQ/TRIG/U3/U2/CONFIG[period][20]} {ACQ/TRIG/U3/U2/CONFIG[period][21]} {ACQ/TRIG/U3/U2/CONFIG[period][22]} {ACQ/TRIG/U3/U2/CONFIG[period][23]} {ACQ/TRIG/U3/U2/CONFIG[period][24]} {ACQ/TRIG/U3/U2/CONFIG[period][25]} {ACQ/TRIG/U3/U2/CONFIG[period][26]} {ACQ/TRIG/U3/U2/CONFIG[period][27]} {ACQ/TRIG/U3/U2/CONFIG[period][28]} {ACQ/TRIG/U3/U2/CONFIG[period][29]} {ACQ/TRIG/U3/U2/CONFIG[period][30]} {ACQ/TRIG/U3/U2/CONFIG[period][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[high_time][0]} {ACQ/TRIG/U3/U2/CONFIG[high_time][1]} {ACQ/TRIG/U3/U2/CONFIG[high_time][2]} {ACQ/TRIG/U3/U2/CONFIG[high_time][3]} {ACQ/TRIG/U3/U2/CONFIG[high_time][4]} {ACQ/TRIG/U3/U2/CONFIG[high_time][5]} {ACQ/TRIG/U3/U2/CONFIG[high_time][6]} {ACQ/TRIG/U3/U2/CONFIG[high_time][7]} {ACQ/TRIG/U3/U2/CONFIG[high_time][8]} {ACQ/TRIG/U3/U2/CONFIG[high_time][9]} {ACQ/TRIG/U3/U2/CONFIG[high_time][10]} {ACQ/TRIG/U3/U2/CONFIG[high_time][11]} {ACQ/TRIG/U3/U2/CONFIG[high_time][12]} {ACQ/TRIG/U3/U2/CONFIG[high_time][13]} {ACQ/TRIG/U3/U2/CONFIG[high_time][14]} {ACQ/TRIG/U3/U2/CONFIG[high_time][15]} {ACQ/TRIG/U3/U2/CONFIG[high_time][16]} {ACQ/TRIG/U3/U2/CONFIG[high_time][17]} {ACQ/TRIG/U3/U2/CONFIG[high_time][18]} {ACQ/TRIG/U3/U2/CONFIG[high_time][19]} {ACQ/TRIG/U3/U2/CONFIG[high_time][20]} {ACQ/TRIG/U3/U2/CONFIG[high_time][21]} {ACQ/TRIG/U3/U2/CONFIG[high_time][22]} {ACQ/TRIG/U3/U2/CONFIG[high_time][23]} {ACQ/TRIG/U3/U2/CONFIG[high_time][24]} {ACQ/TRIG/U3/U2/CONFIG[high_time][25]} {ACQ/TRIG/U3/U2/CONFIG[high_time][26]} {ACQ/TRIG/U3/U2/CONFIG[high_time][27]} {ACQ/TRIG/U3/U2/CONFIG[high_time][28]} {ACQ/TRIG/U3/U2/CONFIG[high_time][29]} {ACQ/TRIG/U3/U2/CONFIG[high_time][30]} {ACQ/TRIG/U3/U2/CONFIG[high_time][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][0]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][1]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][2]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][3]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][4]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][5]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][6]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][7]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][8]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][9]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][10]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][11]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][12]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][13]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][14]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][15]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][16]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][17]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][18]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][19]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][20]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][21]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][22]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][23]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][24]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][25]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][26]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][27]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][28]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][29]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][30]} {ACQ/TRIG/U3/U2/CONFIG[seq_framecount][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[trig_activ][0]} {ACQ/TRIG/U3/U2/CONFIG[trig_activ][1]} {ACQ/TRIG/U3/U2/CONFIG[trig_activ][2]} {ACQ/TRIG/U3/U2/CONFIG[trig_activ][3]} {ACQ/TRIG/U3/U2/CONFIG[trig_activ][4]} {ACQ/TRIG/U3/U2/CONFIG[trig_activ][5]} {ACQ/TRIG/U3/U2/CONFIG[trig_activ][6]} {ACQ/TRIG/U3/U2/CONFIG[trig_activ][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[mode][0]} {ACQ/TRIG/U3/U2/CONFIG[mode][1]} {ACQ/TRIG/U3/U2/CONFIG[mode][2]} {ACQ/TRIG/U3/U2/CONFIG[mode][3]} {ACQ/TRIG/U3/U2/CONFIG[mode][4]} {ACQ/TRIG/U3/U2/CONFIG[mode][5]} {ACQ/TRIG/U3/U2/CONFIG[mode][6]} {ACQ/TRIG/U3/U2/CONFIG[mode][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[acq_window]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[force_high]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[run]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {ACQ/TRIG/U3/U2/CONFIG[seq_trigsource]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list ACQ/TRIG/U3/U2/fpa_trig_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list ACQ/TRIG/U3/U2/fpa_trig_param_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {ACQ/TRIG/U3/U2/fpa_trig_param_i[acq_window]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {ACQ/TRIG/U3/U2/fpa_trig_param_i[run]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list U3/U5/U4/HW_DRIVER_EN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list ACQ/TRIG/U3/U2/integration_detect]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list ACQ/TRIG/U3/U2/INTERNAL_PULSE]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list ACQ/TRIG/U3/U2/internal_pulse_cntraz_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list ACQ/TRIG/U3/U2/raw_pulse_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list ACQ/TRIG/U3/U2/seq_delay_enable_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list ACQ/TRIG/U3/U2/seq_enable_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list ACQ/TRIG/U3/U2/seq_trig_i]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 8 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {U3/U5/U2/U3/new_cfg_num[0]} {U3/U5/U2/U3/new_cfg_num[1]} {U3/U5/U2/U3/new_cfg_num[2]} {U3/U5/U2/U3/new_cfg_num[3]} {U3/U5/U2/U3/new_cfg_num[4]} {U3/U5/U2/U3/new_cfg_num[5]} {U3/U5/U2/U3/new_cfg_num[6]} {U3/U5/U2/U3/new_cfg_num[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 8 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {U3/U5/U2/U3/present_cfg_num[0]} {U3/U5/U2/U3/present_cfg_num[1]} {U3/U5/U2/U3/present_cfg_num[2]} {U3/U5/U2/U3/present_cfg_num[3]} {U3/U5/U2/U3/present_cfg_num[4]} {U3/U5/U2/U3/present_cfg_num[5]} {U3/U5/U2/U3/present_cfg_num[6]} {U3/U5/U2/U3/present_cfg_num[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 40 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {U3/U5/U2/U3/present_cfg[0]} {U3/U5/U2/U3/present_cfg[1]} {U3/U5/U2/U3/present_cfg[2]} {U3/U5/U2/U3/present_cfg[3]} {U3/U5/U2/U3/present_cfg[4]} {U3/U5/U2/U3/present_cfg[5]} {U3/U5/U2/U3/present_cfg[6]} {U3/U5/U2/U3/present_cfg[7]} {U3/U5/U2/U3/present_cfg[8]} {U3/U5/U2/U3/present_cfg[9]} {U3/U5/U2/U3/present_cfg[10]} {U3/U5/U2/U3/present_cfg[11]} {U3/U5/U2/U3/present_cfg[12]} {U3/U5/U2/U3/present_cfg[13]} {U3/U5/U2/U3/present_cfg[14]} {U3/U5/U2/U3/present_cfg[15]} {U3/U5/U2/U3/present_cfg[16]} {U3/U5/U2/U3/present_cfg[17]} {U3/U5/U2/U3/present_cfg[18]} {U3/U5/U2/U3/present_cfg[19]} {U3/U5/U2/U3/present_cfg[20]} {U3/U5/U2/U3/present_cfg[21]} {U3/U5/U2/U3/present_cfg[22]} {U3/U5/U2/U3/present_cfg[23]} {U3/U5/U2/U3/present_cfg[24]} {U3/U5/U2/U3/present_cfg[25]} {U3/U5/U2/U3/present_cfg[26]} {U3/U5/U2/U3/present_cfg[27]} {U3/U5/U2/U3/present_cfg[28]} {U3/U5/U2/U3/present_cfg[29]} {U3/U5/U2/U3/present_cfg[30]} {U3/U5/U2/U3/present_cfg[31]} {U3/U5/U2/U3/present_cfg[32]} {U3/U5/U2/U3/present_cfg[33]} {U3/U5/U2/U3/present_cfg[34]} {U3/U5/U2/U3/present_cfg[35]} {U3/U5/U2/U3/present_cfg[36]} {U3/U5/U2/U3/present_cfg[37]} {U3/U5/U2/U3/present_cfg[38]} {U3/U5/U2/U3/present_cfg[39]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 40 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {U3/U5/U2/U3/new_cfg[0]} {U3/U5/U2/U3/new_cfg[1]} {U3/U5/U2/U3/new_cfg[2]} {U3/U5/U2/U3/new_cfg[3]} {U3/U5/U2/U3/new_cfg[4]} {U3/U5/U2/U3/new_cfg[5]} {U3/U5/U2/U3/new_cfg[6]} {U3/U5/U2/U3/new_cfg[7]} {U3/U5/U2/U3/new_cfg[8]} {U3/U5/U2/U3/new_cfg[9]} {U3/U5/U2/U3/new_cfg[10]} {U3/U5/U2/U3/new_cfg[11]} {U3/U5/U2/U3/new_cfg[12]} {U3/U5/U2/U3/new_cfg[13]} {U3/U5/U2/U3/new_cfg[14]} {U3/U5/U2/U3/new_cfg[15]} {U3/U5/U2/U3/new_cfg[16]} {U3/U5/U2/U3/new_cfg[17]} {U3/U5/U2/U3/new_cfg[18]} {U3/U5/U2/U3/new_cfg[19]} {U3/U5/U2/U3/new_cfg[20]} {U3/U5/U2/U3/new_cfg[21]} {U3/U5/U2/U3/new_cfg[22]} {U3/U5/U2/U3/new_cfg[23]} {U3/U5/U2/U3/new_cfg[24]} {U3/U5/U2/U3/new_cfg[25]} {U3/U5/U2/U3/new_cfg[26]} {U3/U5/U2/U3/new_cfg[27]} {U3/U5/U2/U3/new_cfg[28]} {U3/U5/U2/U3/new_cfg[29]} {U3/U5/U2/U3/new_cfg[30]} {U3/U5/U2/U3/new_cfg[31]} {U3/U5/U2/U3/new_cfg[32]} {U3/U5/U2/U3/new_cfg[33]} {U3/U5/U2/U3/new_cfg[34]} {U3/U5/U2/U3/new_cfg[35]} {U3/U5/U2/U3/new_cfg[36]} {U3/U5/U2/U3/new_cfg[37]} {U3/U5/U2/U3/new_cfg[38]} {U3/U5/U2/U3/new_cfg[39]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 3 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {U3/U5/U4/prog_ctrl_fsm[0]} {U3/U5/U4/prog_ctrl_fsm[1]} {U3/U5/U4/prog_ctrl_fsm[2]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 3 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {U3/U5/U4/hw_seq_fsm[0]} {U3/U5/U4/hw_seq_fsm[1]} {U3/U5/U4/hw_seq_fsm[2]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list U3/U5/U4/fpa_client_done]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list U3/U5/U2/U3/fpa_error_i]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list U3/U5/U4/fpa_first_cfg_done]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list U3/U5/U4/fpa_intf_cfg_up2date]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list U3/U5/U2/U3/new_cfg_num_pending]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list U3/U5/U2/U3/new_cfg_pending]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list U3/U5/U4/PROG_DONE]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list U3/U5/U4/PROG_EN]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list U3/U5/U4/PROG_RQST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list U3/U5/U4/readout_i]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list U3/U5/U4/run_fpa_prog_client]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list U3/U5/U2/U3/SPI_DONE]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe19]
set_property port_width 1 [get_debug_ports u_ila_1/probe19]
connect_debug_port u_ila_1/probe19 [get_nets [list U3/U5/U4/update_fpa_cfg]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe20]
set_property port_width 1 [get_debug_ports u_ila_1/probe20]
connect_debug_port u_ila_1/probe20 [get_nets [list U3/U5/U4/update_fpa_part_only]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe21]
set_property port_width 1 [get_debug_ports u_ila_1/probe21]
connect_debug_port u_ila_1/probe21 [get_nets [list U3/U5/U4/valid_prog_rqst]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_DOUT]
