copy d:\telops\fir-00251-Proc\src\XADC\driver\*.c d:\telops\fir-00251-Proc\src\XADC\driver\*.cpp
copy d:\telops\fir-00251-Proc\src\sw\*.c d:\telops\fir-00251-Proc\src\sw\*.cpp
copy d:\telops\fir-00251-Common\Software\*.c d:\telops\fir-00251-Common\Software\*.cpp
copy D:\Telops\FIR-00251-Proc\src\Hder\Drivers\*.c D:\Telops\FIR-00251-Proc\src\Hder\Drivers\*.cpp
copy D:\Telops\FIR-00251-Proc\src\FPA\PelicanD\Drivers\*.c D:\Telops\FIR-00251-Proc\src\FPA\PelicanD\Drivers\*.cpp
copy D:\Telops\FIR-00251-Proc\src\ExposureTime\Drivers\*.c D:\Telops\FIR-00251-Proc\src\ExposureTime\Drivers\*.cpp
copy D:\Telops\FIR-00251-Proc\src\Trig\Drivers\*.c D:\Telops\FIR-00251-Proc\src\Trig\Drivers\*.cpp
copy D:\Telops\FIR-00251-Proc\src\Calibration\Drivers\*.c D:\Telops\FIR-00251-Proc\src\Calibration\Drivers\*.cpp
copy D:\Telops\FIR-00251-Common\VHDL\Lut\driver\*.c D:\Telops\FIR-00251-Common\VHDL\Lut\driver\*.cpp